version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: scripts/clear_html_directory.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_web_server.sh
      timeout: 300
      runas: root
