version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/streaming-application/

hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
